### ISSUE TITLE
Update the README.md to match the MBL master -LimPID- model path

### ISSUE THREAD

**Issue by Helarga** [lbl-srg/docker-ubuntu-jmodelica#11]
The current README.md file points to the LimPID model on  

Buildings.Controls.OBC.CDL.Continuous.Validation.LimPID

While the new path  for this model at the MBL master branch is

Buildings.Controls.Continuous.Examples.LimPID

N.B.
The "model" path at the jmodelica.py is 
model="Buildings.Utilities.Psychrometrics.Examples.DewPointTemperature"

**Comment by mwetter** [comment]
Thanks for pointing this out. I corrected it in https://github.com/lbl-srg/docker-ubuntu-jmodelica/blob/master/README.md

**Comment by Helarga** [comment]
sure! thank you.
