### ISSUE TITLE
A sincere question

### ISSUE THREAD

**Issue by yaoguaijiao** [lbl-srg/docker-ubuntu-jmodelica#12]
Hello, I am a Chinese student. After seeing your great project, I ran it and found that the code reported errors. However, my technology stack is only java, scala, and python errors. Can you take a look at it? Is my error picture
![S_2020-12-10_10-33-24](https://user-images.githubusercontent.com/48637361/101714484-a1fb2280-3ad4-11eb-9e67-49325b4825c2.JPG)

**Comment by mwetter** [comment]
This is because the Buildings library is either not downloaded or not on the MODELICAPATH, see the Readme file at https://github.com/lbl-srg/docker-ubuntu-jmodelica

**Comment by yaoguaijiao** [comment]
Hello, do you mean I want to install this Modelica Buildings, and then try to run your docker image?

**Comment by mwetter** [comment]
Yes, you need to install the library, otherwise the model does not exist.
